filebeat.inputs:
- type: log
  enabled: true
  paths:
  - /var/log/nginx/access.log
  - /var/log/nginx/error.log
  fields:
    service: nginx
    environment: dev
  fields_under_root: true

output.logstash:
  hosts: [ "logstash:5044" ]
