global:
  scrape_interval: 15s

scrape_configs:
- job_name: 'node-exporter'
  static_configs:
  - targets: [ 'node-exporter:9100' ]
    labels:
      instance: 'infra-host'

- job_name: 'prometheus'
  static_configs:
  - targets: [ 'localhost:9090' ]
